[tool.doit]
verbosity = 2
backend = "json"

[tool.doitoml]
prefix = ""

[tool.doitoml.paths]
ppt = ["pyproject.toml"]

[tool.doitoml.tokens]
lite = ["jupyter", "lite"]

[tool.doitoml.tasks.greet]
doc = "greet the reader"
actions = [{py = {"dodo:greet" = {kwargs = {whom = "world"}}}}]

[tool.doitoml.tasks.show]
doc = "dump the doit config as YAML"
task_dep = ["greet"]
actions = [{py = {"dodo:dump" = {}}}]

[tool.doitoml.tasks.mermaid]
doc = "show this project as a MermaidJS graph"
task_dep = ["greet", "show"]
actions = [{py = {"dodo:mermaid" = {}}}]
